# Generated by Django 5.0.1 on 2024-01-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logindetails',
            name='login_date',
            field=models.DateTimeField(),
        ),
    ]
