# Generated by Django 5.0.1 on 2024-01-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_logindetails_login_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logindetails',
            name='Emp_code',
            field=models.CharField(),
        ),
    ]
