# Generated by Django 5.0.1 on 2024-01-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_logindetails_emp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logindetails',
            name='Emp_code',
            field=models.CharField(max_length=10),
        ),
    ]
